added LockTime variable
The-Poolz/Locked-pools pull request #133
Opened 2022-12-19 15:53 UTC by YouStillAlive

2022-12-20 09:44 UTC, ashwinarora requested changes

2022-12-20 09:44 UTC, ashwinarora commented on contracts/LockedDealV2.sol
> +        isLocked(_PoolId)
This withdraw function may be used by another contract in a loop, hence we do not want this to fail. `isLocked` Modifier is not needed at all. Let modify `getWithdrawableAmount` method to return `0` before the `CliffTime`.

2022-12-20 09:44 UTC, ashwinarora commented on contracts/LockedDealModifiers.sol
> +        uint256 LockTime;
Let's give this a better name. `CliffTime` would be better.

2022-12-22 12:11 UTC, Lomet approved these changes

2022-12-22 14:08 UTC, ashwinarora approved these changes

2022-12-22 14:08 UTC, merged